# Generated by Django 3.0 on 2019-12-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_online', models.IntegerField(default=0)),
                ('current_time', models.DateTimeField()),
                ('current_temp', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('current_hum', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('time', models.IntegerField(default=0)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
