# Generated by Django 3.0 on 2019-12-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191220_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='time_stamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
